spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.ltqogvirizrnnwinzdjl
spring.datasource.password=BharatDevicesPrd1
spring.datasource.driver-class-name=org.postgresql.Driver

# Set dialect explicitly so Hibernate doesn't fail if connectivity drops on startup
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect