server.port=${PORT:8089}
spring.datasource.url=${DB_URL:jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.username=${DB_USERNAME:postgres.ltqogvirizrnnwinzdjl}
spring.datasource.password=${DB_PASSWORD:BharatDevicesPrd1}
spring.datasource.driver-class-name=org.postgresql.Driver

# Set dialect explicitly so Hibernate doesn't fail if connectivity drops on startup
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=VGhpc0lzQVN1ZmZpY2llbnRseUxvbmdTZWNyZXRLZXlGb3JKV1QxMjM0NTY=
jwt.expiration=86400000